spring.application.name=Educational Quality Project

# MongoDB Configuration
# Cole aqui sua Connection String do MongoDB Atlas:
# Exemplo: mongodb+srv://<user>:<password>@cluster0.abcde.mongodb.net/database?retryWrites=true&w=majority
spring.data.mongodb.uri=SUA_URI_AQUI

# Server Configuration
server.port=8080